### PR TITLE
Setting no longer uses builders

### PR DESCRIPTION
**Pull request by yagel15637**
I tested it and it all works right, setting declarations should now be waaay shorter and cleaner.

### CODE REVIEW

**Comment by yagel15637** [comment]
by the way, I like your base, expect to see me here a lot :)

**Comment by Katatje** [comment]
Cool! Thanks :^)

**Comment by Katatje** [comment]
I will prob be working on this a lot soon

**Comment by yagel15637** [comment]
I made a sprint module which ill make a pr of soon

**Pull request merged**
